# Generated by Django 2.1.7 on 2019-04-07 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0002_basicdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='firstName',
            field=models.CharField(max_length=32, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Devices.Hospital', verbose_name='Szpital'),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='lastName',
            field=models.CharField(max_length=64, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='caretaker',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='device',
            name='caretaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Devices.Caretaker', verbose_name='Opiekun'),
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Devices.DeviceType', verbose_name='Typ urządzenia'),
        ),
        migrations.AlterField(
            model_name='device',
            name='guaranteeDate',
            field=models.DateField(verbose_name='Data gwarancji'),
        ),
        migrations.AlterField(
            model_name='device',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Devices.Hospital', verbose_name='Szpital'),
        ),
        migrations.AlterField(
            model_name='device',
            name='installationDate',
            field=models.DateField(verbose_name='Data instalacji'),
        ),
        migrations.AlterField(
            model_name='device',
            name='lastMaintenance',
            field=models.DateField(verbose_name='Ostatni przegląd'),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Devices.Manufacturer', verbose_name='Producent'),
        ),
        migrations.AlterField(
            model_name='device',
            name='nextMaintenance',
            field=models.DateField(verbose_name='Następny przegląd'),
        ),
        migrations.AlterField(
            model_name='device',
            name='sn',
            field=models.CharField(max_length=13, verbose_name='Numer seryjny'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=128, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.CharField(max_length=64, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Telefon'),
        ),
    ]
