# Generated by Django 2.1.7 on 2019-03-28 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registeredDate', models.DateField(auto_now_add=True, verbose_name='Registered date')),
                ('isCompleted', models.BooleanField(default=False, verbose_name='Completed')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ServiceJobs.Job', verbose_name='Job')),
                ('started', models.DateField(verbose_name='Started date')),
                ('finished', models.DateField(verbose_name='Finished date')),
                ('workHours', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Engineer')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='addedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
        ),
        migrations.AddField(
            model_name='job',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Devices.Device', verbose_name='Device'),
        ),
        migrations.AddField(
            model_name='job',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Devices.Hospital', verbose_name='Hospital'),
        ),
        migrations.AddField(
            model_name='job',
            name='jobType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Devices.JobType', verbose_name='Job type'),
        ),
    ]
