# Generated by Django 2.1.7 on 2019-03-24 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=32, verbose_name='First name')),
                ('lastName', models.CharField(max_length=64, verbose_name='Last name')),
                ('phone', models.CharField(max_length=16, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('sn', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='Serial number')),
                ('modelName', models.CharField(max_length=64, verbose_name='Model')),
                ('installation', models.DateField(verbose_name='Installation date')),
                ('guaranteeDate', models.DateField(verbose_name='Guarantee date')),
                ('lastMaintenance', models.DateField(verbose_name='Last maintenance')),
                ('nextMaintenance', models.DateField(verbose_name='Next maintenance')),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServiceJobs.Caretaker', verbose_name='Caretaker')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('address', models.CharField(max_length=128, verbose_name='Address')),
                ('phone', models.CharField(max_length=16, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.DateField(auto_now_add=True, verbose_name='Registered date')),
                ('scheduled', models.DateField(verbose_name='Scheduled date')),
                ('isCompleted', models.BooleanField(default=False, verbose_name='Completed')),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ServiceJobs.Job', verbose_name='Job')),
                ('started', models.DateField(verbose_name='Started date')),
                ('finished', models.DateField(verbose_name='Finished date')),
                ('workHours', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Engineer')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceJobs.Device', verbose_name='Device'),
        ),
        migrations.AddField(
            model_name='job',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceJobs.Hospital', verbose_name='Hospital'),
        ),
        migrations.AddField(
            model_name='job',
            name='jobType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServiceJobs.JobType', verbose_name='Job type'),
        ),
        migrations.AddField(
            model_name='device',
            name='deviceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServiceJobs.DeviceType', verbose_name='Device type'),
        ),
        migrations.AddField(
            model_name='device',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceJobs.Hospital', verbose_name='Hospital'),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServiceJobs.Manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceJobs.Hospital', verbose_name='Hospital'),
        ),
    ]
