# Generated by Django 2.1.7 on 2019-04-06 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Devices', '0002_basicdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registeredDate', models.DateField(auto_now_add=True, verbose_name='Registered date')),
                ('isCompleted', models.BooleanField(default=False, verbose_name='Completed')),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ServiceJobs.Job', verbose_name='Job')),
                ('startDateTime', models.DateTimeField(verbose_name='Start')),
                ('endDateTime', models.DateTimeField(verbose_name='End')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Engineer')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ServiceJobs.Job', verbose_name='Job')),
                ('startedDate', models.DateField(default=django.utils.timezone.now, verbose_name='Started date')),
                ('finishedDate', models.DateField(default=django.utils.timezone.now, verbose_name='Finished date')),
                ('workHours', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Engineer')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='addedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
        ),
        migrations.AddField(
            model_name='job',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Devices.Device', verbose_name='Device'),
        ),
        migrations.AddField(
            model_name='job',
            name='jobType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ServiceJobs.JobType', verbose_name='Job type'),
        ),
    ]
